site_name: Mathematical Dimensions
theme:
  name: material
  palette: 
    - primary: amber

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav: 
  - first.ipynb

plugins: 
  - mknotebooks
  

