site_name: Mathematical Dimensions
#theme:
#  name: material
nav: 
  - first.ipynb

plugins: 
  - mknotebooks
  
theme:
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/waether-night
        name: Switch to light mode
